config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from rest_framework_jwt.views import obtain_jwt_token
from nomadgram import views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("rest-auth/", include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path(
        "users/",
        include("nomadgram.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    
    # Your stuff: custom urls includes go here
    path("images/",include('nomadgram.images.urls',namespace = 'images'),),
    path("notifications/",include('nomadgram.notifications.urls', namespace = 'notifications')),
    path("",views.ReactAppView.as_view()),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

nomadgram/images/urls.py
from django.conf.urls import url
from . import views

app_name = 'images'
urlpatterns = [
    url(
        regex = r'^$',
        view = views.Images.as_view(),
        name = 'feed'
    ),
    url(
        regex = r'^(?P<image_id>\d+)/like/$',
        view = views.ImageDetail.as_view(),
        name = 'image_detail'
    ),
    url(
        regex = r'^(?P<image_id>\d+)/likes/$',
        view = views.LikeImage.as_view(),
        name ='like_image'
    ),
    url(
        regex = r'^(?P<image_id>\d+)/unlikes/$',
        view = views.UnLikeImage.as_view(),
        name ='unlike_image'
    ),
    url(
        regex = r'^(?P<image_id>\d+)/comments/$',
        view = views.CommentOnImage.as_view(),
        name ='comment_image'
    ),
    url(
        regex = r'^(?P<image_id>\d+)/comments/(?P<comment_id>\d+)/$',
        view = views.ModerateComments.as_view(),
        name ='moderate_comments'
    ),
    url(
        regex = r'^comments/(?P<comment_id>\d+)/$',
        view = views.Comment.as_view(),
        name = 'comment',
    ),
    url(
        regex = r'^search/$',
        view = views.Search.as_view(),
        name = 'search'
    )
]

nomadgram/notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'
urlpatterns = [
    path(
        "",
        view = views.Notification.as_view(),
        name = 'notification'
    )
]

nomadgram/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path(
        'login/facebook/',
        view = views.FacebookLogin.as_view(),
        name='fb_login'
    ),
    path(
        "explore",
        view = views.ExploreUser.as_view(),
        name = "explore_user"
    ),
    path(
        "<int:user_id>/follow/",
        view = views.FollowUser.as_view(),
        name = "follow_user"
    ),
    path(
        "<int:user_id>/unfollow/",
        view = views.UnFollowUser.as_view(),
        name = "unfollow_user"
    ),
    path(
        "<str:username>/followers/",
        view = views.UserFollowers.as_view(),
        name = "user_followers"
    ),
    path(
        "<str:username>/following/",
        view = views.UserFollowing.as_view(),
        name = "user_following"
    ),
    path(
        "search",
        view = views.Search.as_view(),
        name = "user_search"
    ),
    path(
        "<str:username>/",
        view = views.UserProfile.as_view(),
        name = "user_profile"
    ),
    path(
        "<str:username>/password/",
        view = views.ChangePassword.as_view(),
        name = "change_password"
    )
]


"""
example
    path("", view=views.UserListView.as_view(), name="list"),
    path("~redirect/", view=views.UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>/",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
"""

nomadgram/images/models.py
from django.db import models
from nomadgram.users import models as user_models
from django.utils.encoding import python_2_unicode_compatible
from taggit.managers import TaggableManager
from django.contrib.humanize.templatetags.humanize import naturaltime
# Create your models here.

@python_2_unicode_compatible
class TimeStampedModel(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:#anything that is not field
        abstract = True #abstract, then it will not connect to database

@python_2_unicode_compatible
class Image(TimeStampedModel):

    file = models.ImageField()
    location = models.CharField(max_length = 140)
    caption = models.TextField()
    creator = models.ForeignKey(user_models.User,related_name='images',on_delete = models.CASCADE, null = True)
    tags = TaggableManager()

    @property
    def like_count(self):
        return self.like_set.all().count()

    @property
    def comment_count(self):
        return self.comments.all().count()

    @property
    def natural_time(self):
        return naturaltime(self.created_at)

    def __str__(self):
        return ' {} - {} '.format(self.location, self.caption)
    
    class Meta:
        ordering = ['-created_at']
    
@python_2_unicode_compatible
class Comment(TimeStampedModel):
    
    message = models.TextField(max_length = 140)
    creator = models.ForeignKey(user_models.User,on_delete = models.CASCADE, null = True)
    image = models.ForeignKey(Image,on_delete = models.CASCADE, null = True, related_name= 'comments')  

    def __str__(self):
        return self.message

@python_2_unicode_compatible
class Like(TimeStampedModel):
    
    creator = models.ForeignKey(user_models.User,on_delete = models.CASCADE)
    image = models.ForeignKey(Image,on_delete = models.CASCADE)  

    def __str__(self):
        return 'User:{} - Image Caption:{}'.format(self.creator.username, self.image.caption)

nomadgram/notifications/models.py
from django.db import models
from nomadgram.users import models as user_models
from nomadgram.images import models as image_models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Notification(image_models.TimeStampedModel):
    
    TYPE_CHOICES = (
        ('like','Like'),
        ('comment','Comment'),
        ('follow','Follow')
    )
    
    creator = models.ForeignKey(user_models.User,on_delete = models.CASCADE,related_name='creator')
    to = models.ForeignKey(user_models.User,on_delete = models.CASCADE,related_name='to')
    notification_type = models.CharField(max_length = 20, choices = TYPE_CHOICES)
    image = models.ForeignKey(image_models.Image,on_delete = models.CASCADE, null=True, blank=True)
    comment = models.TextField(null=True,blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return 'From: {} - To: {}'.format(self.creator,self.to)

nomadgram/images/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . import models, serializers
from nomadgram.notifications import views as notification_views
# Create your views here.
from nomadgram.users import models as user_models
from nomadgram.users import serializers as user_serializers


class Images(APIView):
    
    def get(self, request, format=None):
        
        user = request.user

        following_users = user.following.all()

        image_list = []

        for following_user in following_users:
            
            user_images = following_user.images.all()[:2]

            for image in user_images:
                
                image_list.append(image)
        
        my_images = user.images.all()[:2]

        for image in my_images:
            
            image_list.append(image)

        sorted_list = sorted(image_list, key = lambda image:image.created_at, reverse = True)

        serializer = serializers.ImageSerializer(sorted_list, many=True, context = {'request': request})

        return Response(serializer.data)

    def post(self, request, format = None):

        user = request.user

        serializer =serializers.InputImageSerializer(data = request.data)

        if serializer.is_valid():
            
            serializer.save(creator = user)

            return Response(data = serializer.data , status = status.HTTP_200_OK)
        
        else:
            return Response(data = serializer.errors,status= status.HTTP_400_BAD_REQUEST)
            

class ImageDetail(APIView):
    
    def find_own_image(self, image_id, user):
        
        try:
            image = models.Image.objects.get(id= image_id, creator = user)
            return image
        except models.Image.DoesNotExist:
            return None
        
    
    def get(self,request,image_id,format=None):

        try:
            image = models.Image.objects.get(id = image_id)
        
        except models.Image.DoesNotExist:
            return Response(status = status.HTTP_404_NOT_FOUND)
        
        serializer = serializers.ImageSerializer(image, context = {'request': request})

        return Response(data = serializer.data, status = status.HTTP_200_OK)

    def put(self, request,image_id, format = None):
        
        user = request.user

        image = self.find_own_image(image_id,user)

        if image is None:
            return Response(status = status.HTTP_400_BAD_REQUEST)
        
        serializer = serializers.InputImageSerializer(image, data = request.data, partial = True)

        if serializer.is_valid():
            
            serializer.save()

            return Response(data = serializer.data , status = status.HTTP_200_OK)
        else:
            return Response(data = serializer.errors ,status = status.HTTP_400_BAD_REQUEST)

    def delete(self,request,image_id,format = None):
        
        user = request.user

        image = self.find_own_image(image_id,user)

        if image is None:
            return Response(status = status.HTTP_400_BAD_REQUEST)

        image.delete()

        return Response(status = status.HTTP_204_NO_CONTENT)



class LikeImage(APIView):
    
    def get(self,request,image_id,format= None):
        
        likes = models.Like.objects.filter(image = image_id)

        likes_creator_list = likes.values('creator_id')

        users = user_models.User.objects.filter(id__in = likes_creator_list)

        serializer = user_serializers.ListUserSerializer(users, many = True)

        return Response(data = serializer.data, status= status.HTTP_200_OK)

    
    def post(self, request, image_id,format= None):
        
        user = request.user
        
        try:
            found_image = models.Image.objects.get(id = image_id)
        except models.Image.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        try:
            preexisting_like = models.Like.objects.get(
                creator=user,
                image = found_image
            )
            
            return Response(status = status.HTTP_304_NOT_MODIFIED)

        except models.Like.DoesNotExist:
            new_like = models.Like.objects.create(
                creator=user,
                image=found_image
            )

            new_like.save()

            notification_views.notification_create(user,found_image.creator,'like',image = found_image)

        return Response(status=status.HTTP_201_CREATED)

class UnLikeImage(APIView):
    
    def delete(self,request,image_id, format = None):
        
        user = request.user
        
        try:
            found_image = models.Image.objects.get(id = image_id)
        except models.Image.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        try:
            preexisting_like = models.Like.objects.get(
                creator=user,
                image = found_image
            )
            
            preexisting_like.delete()

            return(Response(status = status.HTTP_204_NO_CONTENT))

        except models.Like.DoesNotExist:

            return Response(status=status.HTTP_304_NOT_MODIFIED)
        

class CommentOnImage(APIView):
    
    def post(self, request, image_id,format = None):
        
        user = request.user

        try: 
            found_image = models.Image.objects.get(id=image_id)

        except models.Image.DoesNotExist:

            return Response(status =status.HTTP_404_NOT_FOUND)
        
        serializer = serializers.CommentSerializer(data = request.data)

        if serializer.is_valid():
            
            serializer.save(creator = user, image = found_image)

            notification_views.notification_create(user,found_image.creator,'comment',image=found_image,comment = serializer.data['message'])
            
            return Response (data = serializer.data, status =status.HTTP_201_CREATED)
        
        else:
            
            return Response(data = serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ModerateComments(APIView):
    
    def delete(self, request,image_id, comment_id, format = None):
        
        user = request.user
        
        try: 
            comment = models.Comment.objects.get(
                id = comment_id,image = image_id, image__creator = user)
            comment.delete()

            return Response(status = status.HTTP_204_NO_CONTENT)
        except models.Comment.DoesNotExist:

            return Response(status = status.HTTP_404_NOT_FOUND)


class Comment(APIView):
    
    def delete(self, request, comment_id, format = None):
        
        user = request.user
        
        try: 
            comment = models.Comment.objects.get(id = comment_id, creator = user)
            comment.delete()

            return Response(status = status.HTTP_204_NO_CONTENT)
        except models.Comment.DoesNotExist:

            return Response(status = status.HTTP_404_NOT_FOUND)

class Search(APIView):

    def get(self, request, format = None):

        hashtags = request.query_params.get('hashtags',None)

        if hashtags is not None:

            hashtags = hashtags.split(',')

            images = models.Image.objects.filter(
                tags__name__in = hashtags).distinct()
            
            serializer = serializers.CountImageSerializer(images, many = True)

            return Response(data = serializer.data, status= status.HTTP_200_OK)

        else:
            return Response(status = status.HTTP_400_BAD_REQUEST)

nomadgram/notifications/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . import models, serializers

# Create your views here.

class Notification(APIView):

    def get(self,request,format = None):

        user = request.user

        notification = models.Notification.objects.filter(to = user)

        serializer = serializers.NotificationSerializer(
            notification,many=True)

        return Response(data = serializer.data, status = status.HTTP_200_OK)

def notification_create(creator,to,notification_type,image= None,comment= None):

    notification = models.Notification.objects.create(
        creator = creator,
        to = to,
        notification_type = notification_type,
        image = image,
        comment = comment
    )

    notification.save()

nomadgram/views.py
from django.views.generic import View
from django.http import HttpResponse
from django.conf import settings
import os

class ReactAppView(View):

    def get(self,request):
        try:
            with open(os.path.join(str(settings.ROOT_DIR),'frontend','build','index.html')) as file:
                return HttpResponse(file.read())
        except:
            return HttpResponse(
                """
                index.html not found ! build your React app !!
                """,
                status = 501,
            )

nomadgram/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

nomadgram/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Nomadgram{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="">Nomadgram</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 